# Generated by Django 5.2.16 on 2026-09-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencytaxonomy',
            name='taxonomy_overrides_org',
            field=models.BooleanField(default=False, help_text="If both an organization-scoped profile and a taxonomy-scoped profile from this taxonomy apply to the same criterion, False (the default) assigns the organization-scoped profile, and True assigns this taxonomy's own profile."),
        ),
    ]
