# Generated by Django 5.2.17 on 2026-09-15 12:29

import re

import django.core.validators
import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

import openedx_django_lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_catalog", "0002_pathways"),
        ("openedx_content", "0014_typed_media_id"),
        ("openedx_learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "publishable_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentity",
                    ),
                ),
                (
                    "catalog_pathway",
                    models.OneToOneField(
                        help_text="The learner-facing Catalog Pathway that this Pathway implements.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="openedx_catalog.catalogpathway",
                    ),
                ),
                (
                    "learning_package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="openedx_content.learningpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway",
                "verbose_name_plural": "Pathways",
            },
        ),
        migrations.CreateModel(
            name="PathwayItem",
            fields=[
                (
                    "publishable_entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentity",
                    ),
                ),
                (
                    "item_code",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"},
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[\\w.-]+\\Z"),
                                'Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.',
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="openedx_learning.pathway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Item",
                "verbose_name_plural": "Pathway Items",
            },
        ),
        migrations.CreateModel(
            name="PathwayItemCourseRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_num", models.PositiveIntegerField()),
                (
                    "enrollment_track",
                    openedx_django_lib.fields.MultiCollationCharField(
                        blank=True,
                        db_collations={"mysql": "utf8mb4_bin", "sqlite": "BINARY"},
                        default="",
                        help_text="If this run uses multiple enrollment tracks, the track to enroll the learner in. Leave blank otherwise.",
                        max_length=100,
                    ),
                ),
                (
                    "course_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="openedx_catalog.courserun"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Item Course Run",
                "verbose_name_plural": "Pathway Item Course Runs",
                "ordering": ["order_num"],
            },
        ),
        migrations.CreateModel(
            name="PathwayItemVersion",
            fields=[
                (
                    "publishable_entity_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentityversion",
                    ),
                ),
                (
                    "course_runs",
                    models.ManyToManyField(
                        related_name="fulfilled_pathway_item_versions",
                        through="openedx_learning.PathwayItemCourseRun",
                        to="openedx_catalog.courserun",
                    ),
                ),
                (
                    "pathway_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="openedx_learning.pathwayitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Item Version",
                "verbose_name_plural": "Pathway Item Versions",
            },
        ),
        migrations.AddField(
            model_name="pathwayitemcourserun",
            name="pathway_item_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_run_rows",
                to="openedx_learning.pathwayitemversion",
            ),
        ),
        migrations.CreateModel(
            name="PathwayVersion",
            fields=[
                (
                    "publishable_entity_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="openedx_content.publishableentityversion",
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="openedx_learning.pathway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Version",
                "verbose_name_plural": "Pathway Versions",
            },
        ),
        migrations.CreateModel(
            name="PathwayVersionItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_num", models.PositiveIntegerField()),
                (
                    "pathway_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="version_rows",
                        to="openedx_learning.pathwayitem",
                    ),
                ),
                (
                    "pathway_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_rows",
                        to="openedx_learning.pathwayversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Version Item",
                "verbose_name_plural": "Pathway Version Items",
                "ordering": ["order_num"],
            },
        ),
        migrations.AddField(
            model_name="pathwayversion",
            name="items",
            field=models.ManyToManyField(
                related_name="pathway_versions",
                through="openedx_learning.PathwayVersionItem",
                to="openedx_learning.pathwayitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayitem",
            constraint=models.UniqueConstraint(
                fields=("pathway", "item_code"), name="oel_pathways_item_uniq_pathway_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayitem",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Regex(models.F("item_code"), "^[\\w.-]+\\Z"),
                name="oel_pathways_item_code_regex",
                violation_error_message='Enter a valid "code name" consisting of any letters, numbers, underscores, hyphens, or periods.',
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayitemcourserun",
            constraint=models.UniqueConstraint(
                fields=("pathway_item_version", "course_run"), name="oel_pathways_picr_uniq_version_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayitemcourserun",
            constraint=models.UniqueConstraint(
                fields=("pathway_item_version", "order_num"), name="oel_pathways_picr_uniq_version_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayversionitem",
            constraint=models.UniqueConstraint(
                fields=("pathway_version", "order_num"), name="oel_pathways_pvi_uniq_version_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathwayversionitem",
            constraint=models.UniqueConstraint(
                fields=("pathway_version", "pathway_item"), name="oel_pathways_pvi_uniq_version_item"
            ),
        ),
    ]
