# Generated by Django 5.2.17 on 2026-09-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_learning', '0006_competencycriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencycriterion',
            name='rule_payload_override',
            field=models.JSONField(blank=True, help_text="Overrides rule_profile's rule_payload for this criterion. Set only when rule_profile is null.", null=True),
        ),
        migrations.AlterField(
            model_name='competencycriterion',
            name='rule_type_override',
            field=models.CharField(blank=True, choices=[('Grade', 'Grade')], help_text="Overrides rule_profile's rule_type for this criterion. Set only when rule_profile is null.", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencycriterion',
            name='rule_payload_override',
            field=models.JSONField(blank=True, help_text="Overrides rule_profile's rule_payload for this criterion. Set only when rule_profile is null.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencycriterion',
            name='rule_type_override',
            field=models.CharField(blank=True, choices=[('Grade', 'Grade')], help_text="Overrides rule_profile's rule_type for this criterion. Set only when rule_profile is null.", max_length=32, null=True),
        ),
    ]
