# Generated by Django 5.2.17 on 2026-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_learning", "0010_studentcompetencystatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcompetencycriteriagroup",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalcompetencycriterion",
            name="history_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historicalcompetencyruleprofile",
            name="history_date",
            field=models.DateTimeField(),
        ),
    ]
