"""
Add the UniqueConstraint on CompetencyCriteriaGroup that backstops course-level group creation.
"""
# Generated by Django 5.2.16 on 2026-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_learning', '0013_alter_historicalcompetencycriteriagroup_history_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competencycriteriagroup',
            constraint=models.UniqueConstraint(
                fields=('tag', 'course', 'parent'),
                name='oel_cbe_criteria_group_one_course_group_per_tag_course',
                violation_error_message=(
                    'A competency tag may have at most one course-level CompetencyCriteriaGroup per course.'
                ),
            ),
        ),
    ]
