# Generated by Django 5.2.17 on 2026-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "openedx_learning",
            "0013_alter_historicalcompetencycriteriagroup_history_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="competencycriteriagroup",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Hides this row from the criteria-tree read endpoint by default, without removing it.",
            ),
        ),
        migrations.AddField(
            model_name="competencycriterion",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Hides this row from the criteria-tree read endpoint by default, without removing it.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompetencycriteriagroup",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Hides this row from the criteria-tree read endpoint by default, without removing it.",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompetencycriterion",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Hides this row from the criteria-tree read endpoint by default, without removing it.",
            ),
        ),
    ]
