# Generated by Django 5.2.17 on 2026-10-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_tagging', '0022_tag_external_id_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttag',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hides this association from active use by default, without removing it.'),
        ),
        migrations.AddField(
            model_name='objecttag',
            name='deletion_locked',
            field=models.BooleanField(default=False, help_text='Set when something outside the tagging app depends on this association; a delete archives it instead of removing it.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hides this tag from active use by default, without removing it.'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='archived',
            field=models.BooleanField(default=False, help_text="Hides this taxonomy from active use by default, without removing it. Unlike disabling it with 'enabled', archiving marks the taxonomy as retired."),
        ),
    ]
