# Generated by Django 5.2.11 on 2026-02-11 23:20

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models

import openedx_content.applets.pathways.keys
import openedx_django_lib.fields
import openedx_django_lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_content", "0002_rename_tables_to_openedx_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    openedx_content.applets.pathways.keys.PathwayKeyField(
                        db_column="_key",
                        db_index=True,
                        help_text="Unique identifier: path-v1:{org}+{path_id}",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "org",
                    models.CharField(
                        editable=False,
                        help_text="A temporary placeholder for the organization short name.",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    openedx_django_lib.fields.MultiCollationCharField(
                        db_collations={"mysql": "utf8mb4_unicode_ci", "sqlite": "NOCASE"}, max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=10000)),
                (
                    "sequential",
                    models.BooleanField(
                        default=True,
                        help_text="If True, learners must complete steps in order. If False, steps can be completed in any order.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, this pathway is treated as archived and should not be offered to new learners.",
                    ),
                ),
                (
                    "invite_only",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, users can only enroll if they are on the allowlist. This is True by default to prevent accidentally exposing learning paths to all users. Only enrolled users can see this learning path.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="It can include any additional information about the pathway, such as its duration, difficulty level,learning outcomes, etc. This field is not used by the core pathway logic. Instead, it aims to provide flexibility for operators to store additional information and process it in plugins.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway",
                "verbose_name_plural": "Pathways",
            },
        ),
        migrations.CreateModel(
            name="PathwayEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Indicates whether the learner is enrolled."),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="openedx_content.pathway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathway_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Enrollment",
                "verbose_name_plural": "Pathway Enrollments",
            },
        ),
        migrations.CreateModel(
            name="PathwayEnrollmentAllowed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Indicates if the enrollment allowance is active"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_allowed",
                        to="openedx_content.pathway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Enrollment Allowed",
                "verbose_name_plural": "Pathway Enrollments Allowed",
            },
        ),
        migrations.CreateModel(
            name="PathwayEnrollmentAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state_transition",
                    models.CharField(
                        choices=[
                            ("from unenrolled to allowed to enroll", "from unenrolled to allowed to enroll"),
                            ("from allowed to enroll to enrolled", "from allowed to enroll to enrolled"),
                            ("from enrolled to enrolled", "from enrolled to enrolled"),
                            ("from enrolled to unenrolled", "from enrolled to unenrolled"),
                            ("from unenrolled to enrolled", "from unenrolled to enrolled"),
                            ("from allowed to enroll to unenrolled", "from allowed to enroll to unenrolled"),
                            ("from unenrolled to unenrolled", "from unenrolled to unenrolled"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        max_length=255,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("org", models.CharField(blank=True, db_index=True, max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, validators=[openedx_django_lib.validators.validate_utc_datetime]
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathway_enrollment_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="openedx_content.pathwayenrollment",
                    ),
                ),
                (
                    "enrollment_allowed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log",
                        to="openedx_content.pathwayenrollmentallowed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Enrollment Audit",
                "verbose_name_plural": "Pathway Enrollment Audits",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PathwayStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "context_key",
                    opaque_keys.edx.django.models.LearningContextKeyField(
                        help_text="Opaque key of the learning context (e.g. 'course-v1:OpenedX+DemoX+DemoCourse').",
                        max_length=255,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[("course", "Course"), ("pathway", "Pathway")],
                        help_text="Type of learning context this step references.",
                        max_length=32,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Position of this step within the pathway (0-indexed)."),
                ),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="openedx_content.pathway"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Step",
                "verbose_name_plural": "Pathway Steps",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="pathwayenrollment",
            constraint=models.UniqueConstraint(fields=("user", "pathway"), name="oel_pathway_enroll_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pathwayenrollmentallowed",
            constraint=models.UniqueConstraint(fields=("pathway", "email"), name="oel_pathway_enrollallow_uniq"),
        ),
        migrations.AddConstraint(
            model_name="pathwaystep",
            constraint=models.UniqueConstraint(fields=("pathway", "order"), name="oel_pathway_step_uniq_order"),
        ),
        migrations.AddConstraint(
            model_name="pathwaystep",
            constraint=models.UniqueConstraint(fields=("pathway", "context_key"), name="oel_pathway_step_uniq_ctx"),
        ),
    ]
