# Generated by Django 5.2.11 on 2026-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_content', '0002_rename_tables_to_openedx_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComponentVersionContent',
            new_name='ComponentVersionMedia',
        ),
        migrations.RenameModel(
            old_name='Content',
            new_name='Media',
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveIndex(
            model_name='componentversionmedia',
            name='oel_cvcontent_c_cv',
        ),
        migrations.RemoveIndex(
            model_name='componentversionmedia',
            name='oel_cvcontent_cv_d',
        ),
        migrations.RenameField(
            model_name='componentversion',
            old_name='contents',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='componentversionmedia',
            old_name='content',
            new_name='media',
        ),
        migrations.AddIndex(
            model_name='componentversionmedia',
            index=models.Index(fields=['media', 'component_version'], name='oel_cvmedia_c_cv'),
        ),
        migrations.AddIndex(
            model_name='componentversionmedia',
            index=models.Index(fields=['component_version', 'media'], name='oel_cvmedia_cv_d'),
        ),
    ]
