# Generated by Django 5.2.10 on 2026-01-14 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oel_tagging', '0018_objecttag_is_copied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCriteriaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ordering', models.PositiveIntegerField()),
                ('logic_operator', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True)),
                ('competency_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_criteria_groups', to='oel_tagging.tag')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='oel_assessment_criteria.assessmentcriteriagroup')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('Grade', 'Grade'), ('MasteryLevel', 'MasteryLevel')], max_length=20)),
                ('rule', models.CharField(max_length=255)),
                ('retake_rule', models.CharField(choices=[('SimpleAverage', 'SimpleAverage'), ('WeightedAverage', 'WeightedAverage'), ('DecayingAverage', 'DecayingAverage'), ('MostRecent', 'MostRecent'), ('Highest', 'Highest')], max_length=20)),
                ('competency_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_criteria', to='oel_tagging.tag')),
                ('object_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_criteria', to='oel_tagging.objecttag')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='oel_assessment_criteria.assessmentcriteriagroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessmentCriteriaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('demonstrated', 'Demonstrated'), ('attempted_not_demonstrated', 'Attempted, Not Demonstrated'), ('not_attempted', 'Not Attempted')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='oel_assessment_criteria.assessmentcriteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_criteria_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompetencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('demonstrated', 'Demonstrated'), ('attempted_not_demonstrated', 'Attempted, Not Demonstrated'), ('not_attempted', 'Not Attempted')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('competency_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_competency_statuses', to='oel_tagging.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='assessmentcriteriagroup',
            index=models.Index(fields=['parent', 'ordering'], name='oel_assessm_parent__7fbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcriteria',
            index=models.Index(fields=['group'], name='oel_assessm_group_i_51f792_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentcriteria',
            index=models.Index(fields=['competency_tag'], name='oel_assessm_compete_690bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessmentcriteriastatus',
            index=models.Index(fields=['assessment_criteria', 'user'], name='oel_assessm_assessm_da136e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcompetencystatus',
            index=models.Index(fields=['competency_tag', 'user'], name='oel_assessm_compete_7e9173_idx'),
        ),
    ]
