# Generated by Django 5.2.10 on 2026-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_assessment_criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcriteria',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessmentcriteriagroup',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
