# Generated by Django 5.2.10 on 2026-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oel_assessment_criteria', '0002_assessmentcriteria_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcriteria',
            name='rule',
        ),
        migrations.AddField(
            model_name='assessmentcriteria',
            name='rule_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
